### ISSUE TITLE
Validating SNS Messages

### ISSUE THREAD

**Issue by leifg** [aws/aws-sdk-core-ruby#211] opened 2015-02-10 14:38 UTC
With v1 I could verify SNS Messages like this:

    AWS::SNS::Message.new(params).authentic?

But in the v2 docs (and code) I have found no reference to this. The only thing I discovered was a post from November 2014 where it is explained, that this feature is not implemented yet. https://forums.aws.amazon.com/message.jspa?messageID=584183

But as v2 is stable now I suppose this feature should be implemented?

**Comment by trevorrowe** [comment] 2015-02-10 23:00
You are correct that this feature has not yet been implemented in the v2 SDK. You can continue using the v1 SDK to verify messages until this functionality has been ported.  Could you re-open this issue against the new repo? We've recently migrated back to the aws/aws-sdk-ruby repo.

**Comment by trevorrowe** [comment] 2015-02-16 17:59
Closed as duplicate of https://github.com/aws/aws-sdk-ruby/issues/709

**Closed by trevorrowe** 2015-02-16 17:59 UTC
Labels: Feature Request
