### ISSUE TITLE
Class for thrown errors has changed, doc is now outdated

### ISSUE THREAD

**Issue by SpencerBrown** [aws/aws-sdk-core-ruby#214] opened 2015-02-17 16:06 UTC
The base class used to be Aws::EC2::Errors::ServiceError, somewhere recently it changed to just Aws::EC2::Errors. I've adapted my code but the documentation needs to be fixed, see

http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Errors.html

and there are probably other places too.

**Comment by trevorrowe** [comment] 2015-02-18 06:53
Closing as a duplicate of https://github.com/aws/aws-sdk-ruby/issues/710

**Closed by trevorrowe** 2015-02-18 06:53 UTC
